### ISSUE TITLE
Save all data to firestore database

### ISSUE THREAD

**Issue by maxbischof** [maxbischof/vocab-trainer#2]
## Value statement
I as a **user**
want to **have permanent access to the tests I created**
so that **I can use the test and see the user data permanently**

## Description
Googles firestore is an easy to implement no-sql database. With its serverless approach there is no need for the express backend server anymore. Therefore the web sdk will be implemented in the client so the data can be written and read from firestore directly.

## Tasks
* [x] Create firebase project and firestore db
* [x] Add maximum costs per day to firebase project
* [x] Add web sdk to client
* [x] Save created test to firestore
* [x] Save user result as subcollection to test on firestore
* [x] Remove express server
* [ ] Deploy to vercel instead of heroku because no backend is needed anymore

## Acceptance criteria
* [ ] Test can be created and read from firestore
* [ ] Test results of user are added to test and can be loaded.

**Comment by maxbischof** [comment]
Note: Maximum costs per day are deprecated. Maximum costs per month can only be set on the billing account in google cloud. The project is currently on the free plan. So no limit has to be set anyway.
