### ISSUE TITLE
Shorter and memorable test links

### ISSUE THREAD

**Issue by maxbischof** [maxbischof/vocab-trainer#5]
## Value statement
I as a **user**
want to **get a link that I can easily handle**
so that **I can quickly open the test**

## Description
Currently the links are based on firestores automatically generated ids. These ids are even case sensitive. The aim would be to have shorter and maybe even memorable links. Therefore test links should consists of 6 digit random numbers.

## Tasks
* [x] Generate random 6 digit number
* [x] Check if number exists in db,
   * [x] if it exists generate new number
   * [x] else generate new test with number as id

## Acceptance criteria
* [x] Test is created with number
